---
title: "Lectures"
output:
  html_document:
    toc: false
---

Check out each week to see what you need to be doing before, during, and after class.

## Lectures {.tabset .tabset-fade}

### Week 2

<b>Before class:</b>  

* Catch up on a few videos from Week 1:
  * [Git, SSH keys, etc.](https://youtu.be/QmWX1TbB2sM)
  * [Tyler solves problem he hit at end of prior video ^](https://youtu.be/MBCjQ6v1Fek)
* Videos for Week 2: 
  * [Intro to R](https://youtu.be/opG_Xcn-t2s)
  * [Filepaths and folder setup](https://youtu.be/cWb3p7vjpfg)
  * [How R thinks about data (Part 1, Vectors)](https://youtu.be/XlBF3oo4yiE)
  * [How R thinks about data (Part 2, Subsetting)](https://youtu.be/6qU9k125oOc)

<b>After class:</b>  

* <a href="https://forms.gle/4P4JK3GWMuXEH2DH6" target="_blank">Post-Class Survey (complete after class)</a>

### Week 3

<b>Before class:</b>  

* Complete the Week 2 homework in the [Assignments tab](https://ucd-cepb.github.io/R-DAVIS/assignments.html)
* We'll complete [How R thinks about data (Part 2, Subsetting)](https://youtu.be/6qU9k125oOc) this week since we didn't finish in class week 2.
* Videos for Week 3: 
  * [How R thinks about data (Part 3, vector math)](https://youtu.be/S61ZbPMsBR4)
  * [How R thinks about data (Part 4, missing values)](https://youtu.be/NGh04hOyx7c)
  * [How R thinks about data (Part 5a, things other than vectors)](https://youtu.be/plnoV9Ds8nQ)
  * [How R thinks about data (Part 5b, factors)](https://youtu.be/3u0Q2jg9Xeo)
  * [Starting with Spreadsheets Part I: Reading in and exploring data](https://youtu.be/fL1ylCS82cU)
  * [Starting with Spreadsheets Part II: Indexing and Subsetting data.frame Objects](https://youtu.be/lqW67USHLcM)
  
<b>After class:</b>  

* <a href="https://forms.gle/4P4JK3GWMuXEH2DH6" target="_blank">Post-Class Survey (complete after class)</a>

### Week 4

<b>Before class:</b>  

* Complete the Week 3 homework in the [Assignments tab](https://ucd-cepb.github.io/R-DAVIS/assignments.html)
* Videos for Week 4:  
  * [Spreadsheet best practices](https://youtu.be/ZpiSc71juf4)
  * [Welcome to the tidyverse](https://youtu.be/JOyZBx5JME0)
  * [Data manipulation Part 1a](https://youtu.be/yjOdk-FYZLw)
  * [Data manipulation Part 1b](https://youtu.be/PtiSeJEZ7Jc)

<b>After class:</b>  

* <a href="https://forms.gle/4P4JK3GWMuXEH2DH6" target="_blank">Post-Class Survey (complete after class)</a>

### Week 5

<b>Before class:</b>  

* Complete the Week 4 homework in the [Assignments tab](https://ucd-cepb.github.io/R-DAVIS/assignments.html)
* Videos for Week 5:
  * Be sure to review Data Manipulation part 1b, which we didn't finish in class last week
  * [Data manipulation Part 2a](https://youtu.be/kzT23-kQIdE)
  * [Data manipulation Part 2b](https://youtu.be/snhv8tRQRB8)

<!------
  * [Data manipulation Part 2](https://www.youtube.com/watch?v=Y7nhagJCCk4&list=PL9RGU7mcuUv6hlpNiICK6Q1NYnBsf-RYk&index=1&t=824s)
* (All videos can be found on the [2021 R-DAVIS video page](https://www.youtube.com/playlist?list=PL9RGU7mcuUv6hlpNiICK6Q1NYnBsf-RYk))
  ------> 

<b>After class:</b>  

* <a href="https://forms.gle/4P4JK3GWMuXEH2DH6" target="_blank">Post-Class Survey (complete after class)</a>

### Week 6

<b>Before class:</b>  

* Complete the Week 5 homework in the [Assignments tab](https://ucd-cepb.github.io/R-DAVIS/assignments.html)

* Videos for Week 6:
  * [Data visualization Part 1a](https://youtu.be/BO-9aFrUcrA)
  * [Data visualization Part 1b](https://youtu.be/OyWtWbZcC6A)

<b>After class:</b>  

* <a href="https://forms.gle/4P4JK3GWMuXEH2DH6" target="_blank">Post-Class Survey (complete after class)</a>

### Week 7

<b>Before class:</b>  

* Complete the Week 6 homework in the [Assignments tab](https://ucd-cepb.github.io/R-DAVIS/assignments.html)
* Videos for Week 7:
  * Data visualization Part 2a
  * Data visualization Part 2b


<!------
  * [Data visualization Part 2A](https://www.youtube.com/watch?v=Xq2lCoNlqH8&list=PL9RGU7mcuUv6hlpNiICK6Q1NYnBsf-RYk&index=2)
  * [Data visualization Part 2B](https://www.youtube.com/watch?v=GDqT7MP2QLA&list=PL9RGU7mcuUv6hlpNiICK6Q1NYnBsf-RYk&index=1)
* (All videos can be found on the [2021 R-DAVIS video page](https://www.youtube.com/playlist?list=PL9RGU7mcuUv6hlpNiICK6Q1NYnBsf-RYk))
  ------> 

<b>After class:</b>  

* <a href="https://forms.gle/4P4JK3GWMuXEH2DH6" target="_blank">Post-Class Survey (complete after class)</a>

### Week 8

<b>Before class:</b>  

* Complete the Week 7 homework in the [Assignments tab](https://ucd-cepb.github.io/R-DAVIS/assignments.html)
* Videos for Week 8:
  * [Dates with Lubridate](https://youtu.be/AI56n5J76SQ)
  * [Function-writing](https://youtu.be/5gAig6AQ4S0)


<!------  
  * [Lubridate](https://www.youtube.com/watch?v=CVgeZf8Av0I&list=PL9RGU7mcuUv6hlpNiICK6Q1NYnBsf-RYk&index=2)
  * [Function writing](https://www.youtube.com/watch?v=DzYaUFy6Ims&list=PL9RGU7mcuUv6hlpNiICK6Q1NYnBsf-RYk&index=1)
* (All videos can be found on the [2021 R-DAVIS video page](https://www.youtube.com/playlist?list=PL9RGU7mcuUv6hlpNiICK6Q1NYnBsf-RYk))
  ------> 

<b>After class:</b>  

* <a href="https://forms.gle/4P4JK3GWMuXEH2DH6" target="_blank">Post-Class Survey (complete after class)</a>


### Week 9

<b>Before class:</b>  

* Complete the Week 8 homework in the [Assignments tab](https://ucd-cepb.github.io/R-DAVIS/assignments.html)
* Videos for Week 9:
  * For loops
  * Map functions

### Finals Week

* Complete the [post-course credit reflection](https://forms.gle/iPvPYs8Zx6EZcpLC9)

